apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidenta
spec:
  template:
    spec:
      containers:
        - name: server
          image: argoproj/argocd:latest
          imagePullPolicy: Always
          command: [incidenta, web]
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: STATIC_ASSETS
              value: /shared/app
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 30
